import type { Project } from "@/types/project";

export const projects: Project[] = [
  {
    slug: "dhwani",
    title: "Dhwani",
    description: "Conversational Agents for Blue-Collar Recruitment (@Dhwanilabs).",
    tech: ["Python", "Next.js", "TypeScript"],
    liveHref: "https://dhwanilabs.com/",
    githubHref: null,
  },
  {
    slug: "upbot",
    title: "Upbot",
    description: "A Value-first, reliable, and scalable uptime monitoring platform",
    tech: ["Next.js", "Redis"],
    liveHref: "https://www.upbot.space/",
    githubHref: null,
  },
  {
    slug: "iterconnect",
    title: "Iterconnect",
    description: "Campus-Connect allows students to connect & share resources.",
    tech: ["Next.js", "Firebase"],
    liveHref: "http://iterconnect.live/explore",
    githubHref: "https://github.com/shaurya35/ITER-Social-Connect",
  },
  {
    slug: "web-wallet",
    title: "Web Wallet",
    description: "A minimal crypto wallet to generate seed phrases and derivation paths.",
    tech: ["Solana Web3.js", "Ethers.js"],
    liveHref: "https://webwallet.shauryacodes.me/",
    githubHref: "https://github.com/shaurya35/solana-web-wallet",
  },
  {
    slug: "philips-greenheart",
    title: "Philips GreenHeart",
    description: "Philips Greenheart monitors your heart health (Ex-@Ownpath).",
    tech: ["React", "TypeScript"],
    liveHref: "https://www.heartprint.in/greenheartprogram/",
    githubHref: null,
  },
  {
    slug: "brixline",
    title: "Brixline",
    description: "Brixline is a tech-enabled Construction-as-a-Service Company (Ex-@Brixline).",
    tech: ["Next.js", "TypeScript"],
    liveHref: "https://brixline-dev.vercel.app/",
    githubHref: "https://github.com/shaurya35/brixline",
  },
  {
    slug: "gobrix",
    title: "Gobrix",
    description: "Gobrix is a tech-enabled Construction-as-a-Service Company (Ex-@Brixline).",
    tech: ["Next.js", "TypeScript"],
    liveHref: "https://brixline-client-main.vercel.app/",
    githubHref: "https://github.com/shaurya35/brixline",
  },
  {
    slug: "xora",
    title: "Xora",
    description: "A modern, responsive frontend UI project with Tailwind.",
    tech: ["Next.js", "Tailwind"],
    liveHref: "https://xora-saas-three.vercel.app/",
    githubHref: "https://github.com/shaurya35/xora-saas",
  },
  {
    slug: "token-liquidity-creator",
    title: "Token Liquidity Creator",
    description: "Solana launchpad to create, mint tokens, and add CP liquidity pools.",
    tech: ["React", "Solana", "Web3.js"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/Token-Liquidity-Creator",
  },
  {
    slug: "ethereum-wallet-adapter",
    title: "Ethereum Wallet Adapter",
    description: "Ethereum wallet connector to interact with ERC-20 contracts on-chain.",
    tech: ["TypeScript", "Wagmi", "Viem"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/Ethereum-wallet-adapter",
  },
  {
    slug: "rust-password-manager",
    title: "Rust Password Manager",
    description: "CLI password manager built in Rust with Actix-web and Docker.",
    tech: ["Rust", "Actix-web", "Docker"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/Rust-PM-be",
  },
  {
    slug: "stockwise",
    title: "Stockwise",
    description: "Stockwise is a Web-app for Inventory management using demand forecasting.",
    tech: ["React", "Express.js"],
    liveHref: "https://stockwise-omega.vercel.app/",
    githubHref: "https://github.com/shaurya35/Stockwise-Inventory-Manager",
  },
  {
    slug: "greenglide",
    title: "GreenGlide",
    description: "GreenGlide is an Web-app addressing Inefficiencies in Urban Waste Management.",
    tech: ["React", "Express.js"],
    liveHref: "https://greenglide-smartwaste-management-system.vercel.app/",
    githubHref: "https://github.com/shaurya35/GreenGlide-SmartWaste-Management-System",
  },
  {
    slug: "motionarteffect",
    title: "MotionArtEffect",
    description: "MotionArtEffect is a replica of an existing website built with React.js",
    tech: ["React", "Tailwind"],
    liveHref: "https://heliverse-task-rose.vercel.app/",
    githubHref: "https://github.com/shaurya35/Heliverse-task",
  },
  {
    slug: "yelpcamp",
    title: "Yelpcamp",
    description: "Yelpcamp is a campsite finder Web-app with Search and Filtering features.",
    tech: ["Express.js", "EJS"],
    liveHref: "https://yelp-camp-taqn.onrender.com/",
    githubHref: "https://github.com/shaurya35/Yelp-Camp",
  },
  {
    slug: "e-learning-platform",
    title: "E-Learning Platform",
    description: "E-learning platform with course management and ML recommendations.",
    tech: ["Next.js", "Express.js", "Python"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/E-Learning-Platform",
  },
  {
    slug: "dpin-uptime",
    title: "DPIN Uptime",
    description: "Uptime monitoring with API, hub, and validator microservices.",
    tech: ["Next.js", "TypeScript", "Node.js"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/dpin-uptime",
  },
  {
    slug: "exness",
    title: "Exness",
    description: "Trading platform with auth, trade management, and a poller service.",
    tech: ["Next.js", "TypeScript", "Prisma"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/exness",
  },
  {
    slug: "coffee-landing-page",
    title: "Coffee Landing Page",
    description: "A Sleek React coffee landing page showcasing varieties and reviews.",
    tech: ["React"],
    liveHref: "https://coffeeinseconds.netlify.app/",
    githubHref: "https://github.com/shaurya35/OCTANET_APRIL",
  },
  {
    slug: "landing-page",
    title: "Landing Page",
    description: "A Responsive landing page built with HTML, CSS, and JavaScript.",
    tech: ["HTML", "CSS"],
    liveHref: "https://prodigy-wd-01-sigma.vercel.app/",
    githubHref: "https://github.com/shaurya35/PRODIGY_WD_01",
  },
  {
    slug: "amazon-clone",
    title: "Amazon Clone",
    description: "An Amazon clone created with HTML and CSS.",
    tech: ["HTML", "CSS"],
    liveHref: "https://amazonbyshaurya.netlify.app/",
    githubHref: "https://github.com/shaurya35/Amazon-Clone",
  },
  {
    slug: "interactive-calendar",
    title: "Interactive Calendar",
    description: "An Interactive calendar developed with Next.js, PostgreSQL.",
    tech: ["Next.js", "Firebase"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/Interactive-Nextjs-Calendar",
  },
];
