import type { Project } from "@/types/project";

export const projects: Project[] = [
  {
    slug: "dhwani",
    title: "Dhwani",
    description:
      "Multilingual voice-AI agent that calls and screens blue-collar job candidates. Talking to 20-30 early customers.",
    tech: ["Python", "Next.js", "TypeScript"],
    liveHref: "https://dhwanilabs.com/",
    githubHref: null,
    image: "/projects/dhwani.jpg",
  },
  {
    slug: "upbot",
    title: "Upbot",
    description:
      "Distributed uptime monitoring on Redis Streams, running health checks from 15+ global locations. 40+ people on the waitlist.",
    tech: ["Next.js", "Redis", "Express"],
    liveHref: "https://www.upbot.space/",
    githubHref: "https://github.com/shaurya35/upbot",
    image: "/projects/upbot.jpg",
  },
  {
    slug: "iterconnect",
    title: "ITERConnect",
    description:
      "Campus developer-networking platform built with a 7-person team. 250+ users, 300+ waitlist, 10+ alumni.",
    tech: ["Next.js", "Firebase", "Express"],
    liveHref: "https://www.iterconnect.com/",
    githubHref: "https://github.com/shaurya35/ITER-Social-Connect",
    image: "/projects/iterconnect.jpg",
  },
  {
    slug: "web-wallet",
    title: "Web Wallet",
    description: "A minimal crypto wallet to generate seed phrases and derivation paths.",
    tech: ["Solana Web3.js", "Ethers.js"],
    liveHref: "https://webwallet.shauryacodes.me/",
    githubHref: "https://github.com/shaurya35/solana-web-wallet",
    image: "/projects/web-wallet.jpg",
  },
  {
    slug: "solana-realtime-indexer",
    title: "Solana Realtime Indexer",
    description:
      "A Rust indexer that decodes Pump.fun and PumpSwap trades on Solana, including CPI-routed trades.",
    tech: ["Rust", "Carbon", "Yellowstone gRPC"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/solana-realtime-indexer",
  },
  {
    slug: "sol-staking-program",
    title: "SOL Staking Program",
    description: "An Anchor program to stake SOL in a PDA and earn time-based reward points.",
    tech: ["Rust", "Anchor", "Solana"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/staking-smart-contract",
  },
  {
    slug: "token-liquidity-creator",
    title: "Token Liquidity Creator",
    description: "Solana launchpad to create, mint tokens, and add CP liquidity pools.",
    tech: ["React", "Solana", "Web3.js"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/Token-Liquidity-Creator",
  },
  {
    slug: "ethereum-wallet-adapter",
    title: "Ethereum Wallet Adapter",
    description: "Ethereum wallet connector to interact with ERC-20 contracts on-chain.",
    tech: ["TypeScript", "Wagmi", "Viem"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/Ethereum-wallet-adapter",
  },
  {
    slug: "rust-password-manager",
    title: "Rust Password Manager",
    description: "CLI password manager built in Rust with Actix-web and Docker.",
    tech: ["Rust", "Actix-web", "Docker"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/Rust-PM-be",
  },
  {
    slug: "philips-greenheart",
    title: "Philips GreenHeart",
    description: "Philips Greenheart monitors your heart health (Ex-@Ownpath).",
    tech: ["React", "TypeScript"],
    liveHref: "https://www.heartprint.in/greenheartprogram/",
    githubHref: null,
    image: "/projects/philips-greenheart.jpg",
  },
  {
    slug: "brixline",
    title: "Brixline",
    description: "Brixline is a tech-enabled Construction-as-a-Service Company (Ex-@Brixline).",
    tech: ["Next.js", "TypeScript"],
    liveHref: "https://brixline-dev.vercel.app/",
    githubHref: "https://github.com/shaurya35/brixline",
    image: "/projects/brixline.jpg",
  },
  {
    slug: "gobrix",
    title: "Gobrix",
    description: "Gobrix is a tech-enabled Construction-as-a-Service Company (Ex-@Brixline).",
    tech: ["Next.js", "TypeScript"],
    liveHref: "https://brixline-client-main.vercel.app/",
    githubHref: "https://github.com/shaurya35/brixline",
    image: "/projects/gobrix.jpg",
  },
  {
    slug: "xora",
    title: "Xora",
    description: "A modern, responsive frontend UI project with Tailwind.",
    tech: ["Next.js", "Tailwind"],
    liveHref: "https://xora-saas-three.vercel.app/",
    githubHref: "https://github.com/shaurya35/xora-saas",
    image: "/projects/xora.jpg",
  },
  {
    slug: "stockwise",
    title: "Stockwise",
    description: "Stockwise is a Web-app for Inventory management using demand forecasting.",
    tech: ["React", "Express.js"],
    liveHref: "https://stockwise-omega.vercel.app/",
    githubHref: "https://github.com/shaurya35/Stockwise-Inventory-Manager",
    image: "/projects/stockwise.jpg",
  },
  {
    slug: "greenglide",
    title: "GreenGlide",
    description: "GreenGlide is an Web-app addressing Inefficiencies in Urban Waste Management.",
    tech: ["React", "Express.js"],
    liveHref: "https://greenglide-smartwaste-management-system.vercel.app/",
    githubHref: "https://github.com/shaurya35/GreenGlide-SmartWaste-Management-System",
    image: "/projects/greenglide.jpg",
  },
  {
    slug: "e-learning-platform",
    title: "E-Learning Platform",
    description: "E-learning platform with course management and ML recommendations.",
    tech: ["Next.js", "Express.js", "Python"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/E-Learning-Platform",
  },
  {
    slug: "dpin-uptime",
    title: "DPIN Uptime",
    description: "Uptime monitoring with API, hub, and validator microservices.",
    tech: ["Next.js", "TypeScript", "Node.js"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/dpin-uptime",
  },
  {
    slug: "exness",
    title: "Exness",
    description: "Trading platform with auth, trade management, and a poller service.",
    tech: ["Next.js", "TypeScript", "Prisma"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/exness",
  },
  {
    slug: "interactive-calendar",
    title: "Interactive Calendar",
    description: "An Interactive calendar developed with Next.js, PostgreSQL.",
    tech: ["Next.js", "Firebase"],
    liveHref: null,
    githubHref: "https://github.com/shaurya35/Interactive-Nextjs-Calendar",
    image: "/projects/interactive-calendar.jpg",
  },
];
