[package]
name = "rust-be"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }
tracing-subscriber = { version = "0.3.23", features = ["fmt"] }
chrono = { version = "0.4.41", features = ["serde"] }
thiserror = "2.0.20"
dotenvy = "0.15.7"
tracing = "0.1.44"
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "tls-native-tls", "postgres", "macros", "migrate", "chrono"] }
pulldown-cmark = "0.13"
